 services:
   trade-bot:
     build: .
     container_name: trade-bot
     env_file:
       - .env
-    volumes:
-      - .:/app
     environment:
       SYMBOL: SOFI
       INTERVAL: m30
    # command: 
    #   override if you want a different default
    #   - sh
    #   - -c
    #   - . .venv/bin/activate && npm run bot -- --symbol=${SYMBOL} --interval=${INTERVAL}
