services:
  trade-bot:
    build: .
    container_name: trade-bot
    env_file:
      - .env
    volumes:
      - .:/app:delegated      # your code
      - tradebot_venv:/app/.venv  # separate venv
    environment:
      SYMBOL: SOFI
      INTERVAL: m30

volumes:
  tradebot_venv:
    # command: 
    #   override if you want a different default
    #   - sh
    #   - -c
    #   - . .venv/bin/activate && npm run bot -- --symbol=${SYMBOL} --interval=${INTERVAL}
