name: CI

on:
  push:    { branches: [main] }
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:       # ← example of adding a service later
        image: redis
        ports: [ "6379:6379" ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # ---------- Python ----------
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Python deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run pytest smoke suite
      env:
        CI: "true"     # tells core.py to skip live login
        PYTHONPATH: ${{ github.workspace }}
      run: pytest tests -q

    # ---------- Node ----------
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Install Node deps
      run: npm ci

    - name: Lint JS (quick ES check)
      run: node -e "console.log('JS OK')"
